#!/bin/bash

if [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS='Linux'
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

cat /proc/net/tcp* | awk '

  match ($4, /0[0-9A-B]/) {
      STATE[$4]++;
  }

  END {
      printf "established.value %d\n", STATE["01"];
      printf "syn_sent.value %d\n",    STATE["02"];
      printf "syn_recv.value %d\n",    STATE["03"];
      printf "fin_wait1.value %d\n",   STATE["04"];
      printf "fin_wait2.value %d\n",   STATE["05"];
      printf "time_wait.value %d\n",   STATE["06"];
      printf "close.value %d\n",       STATE["07"];
      printf "close_wait.value %d\n",  STATE["08"];
      printf "last_ack.value %d\n",    STATE["09"];
      printf "listen.value %d\n",      STATE["0A"];
      printf "closing.value %d\n",     STATE["0B"];
  }'
