package main

import (
	_ "crypto/rand"
	_ "encoding/base64"
	_ "encoding/json"
	_ "io"
	_ "log"
	_ "net/http"
	_ "os"
	_ "time"

	_ "github.com/SonicRoshan/scope"
	_ "github.com/adam-hanna/sessions"
	_ "github.com/adam-hanna/sessions/auth"
	_ "github.com/adam-hanna/sessions/store"
	_ "github.com/adam-hanna/sessions/transport"
	_ "github.com/alexandre-normand/slackscot"
	_ "github.com/alexandre-normand/slackscot/config"
	_ "github.com/alexandre-normand/slackscot/plugins"
	_ "github.com/alexandre-normand/slackscot/store"
	_ "github.com/alexedwards/scs/v2"
	_ "github.com/algoGuy/EasyMIDI/smfio"
	_ "github.com/asticode/go-astilectron-bundler"
	_ "github.com/bogem/id3v2"
	_ "github.com/casbin/casbin/v2"
	_ "github.com/chmike/securecookie"
	_ "github.com/dghubble/gologin"
	_ "github.com/gen2brain/malgo"
	_ "github.com/go-chat-bot/bot"
	_ "github.com/go-chat-bot/plugins/catfacts"
	_ "github.com/go-chat-bot/plugins/catgif"
	_ "github.com/go-chat-bot/plugins/chucknorris"
	_ "github.com/go-chat-bot/plugins/godoc"
	_ "github.com/go-chi/chi"
	_ "github.com/go-telegram-bot-api/telegram-bot-api"
	_ "github.com/goji/httpauth"
	_ "github.com/hajimehoshi/oto"
	_ "github.com/hako/branca"
	_ "github.com/markbates/goth"
	_ "github.com/mengzhuo/cookiestxt"
	_ "github.com/mikespook/gorbac"
	_ "github.com/nikepan/govkbot/v2"
	_ "github.com/o1egl/paseto"
	_ "github.com/oklahomer/go-sarah/v3"
	_ "github.com/oklahomer/go-sarah/v3/slack"
	_ "github.com/olebedev/go-tgbot"
	_ "github.com/olebedev/go-tgbot/client/users"
	_ "github.com/olebedev/go-tgbot/models"
	_ "github.com/onrik/micha"
	_ "github.com/openshift/osin"
	_ "github.com/sashka/signedvalue"
	_ "github.com/sbstjn/hanu"
	_ "github.com/shomali11/slacker"
	_ "github.com/spf13/viper"
	_ "github.com/swithek/sessionup"
	_ "github.com/tosone/minimp3"
	_ "github.com/volatiletech/authboss/v3"
	_ "github.com/xyproto/permissions2"
	_ "github.com/yanzay/tbot/v2"
	_ "github.com/zpatrick/rbac"
	_ "golang.org/x/oauth2"
	_ "gopkg.in/alecthomas/kingpin.v2"
	_ "gopkg.in/telegram-bot-api.v4"
)

func main() {
	return
}
