name: Docker ImageBuild And CI

on:
  push:
    branches: 
      - master
      - release/**
      
jobs:
  docker_file_lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print Docker version & info
        run: |
          docker version && docker info
      
      - name: Lint Dockerfile
        run: |
          docker container run --rm -i hadolint/hadolint:v1.17.6-3-g8da4f4e-alpine < ./files/Dockerfile
          
      - name: Image Build
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_NAME: test
          IMAGE_VERSION: 1.0.0
        run: |
          docker image build -t ${IMAGE_NAME}:${IMAGE_VERSION}
