name: Docker ImageBuild And CI

on:
  push:
    branches: 
      - master
      - release/**

env:
  IMAGE_NAME: test
  IMAGE_VERSION: 1.0.0

  DOCKER_BUILDKIT: 1
  DOCKER_FILE: ./files/Dockerfile

  HADOLINT_IMAGE_VERSION: v1.17.6-3-g8da4f4e-alpine

jobs:
  docker_file_lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print Docker version & info
        run: |
          docker version && docker info
      
      - name: Lint Dockerfile
        run: |
          docker container run --rm -i hadolint/hadolint:${HADOLINT_IMAGE_VERSION} < ${DOCKER_FILE}
          
      - name: Image Build
        run: |
          docker image build -f ${DOCKER_FILE} -t ${IMAGE_NAME}:${IMAGE_VERSION} .

      - name: Image Check
        run: |
          echo "=== ls ===" && docker image ls --no-trunc ${IMAGE_NAME}:${IMAGE_VERSION}
          echo "=== history ===" && docker image history --no-trunc ${IMAGE_NAME}:${IMAGE_VERSION}
          echo "=== inspect ===" && docker image inspect ${IMAGE_NAME}:${IMAGE_VERSION}
