name: Docker ImageBuild And CI

on:
  push:
    branches: 
      - master
      - release/**
      
jobs:
  docker_file_lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print Docker version & info
        run: |
          docker version && docker info
      
      - name: Lint Dockerfile
        run: |
          docker container run --rm -i hadolint/hadolint < ./files/Dockerfile
      
