name: List Repository Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "Listing all files in the repository:"
          ls -R

