name: ShellScript Lint

on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    name: Install ShellScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
          shellcheck --version

      - name: Lint
        run: |
          for sh in $(find . -name *.sh); do echo "====== ${sh} =====" && shellcheck ${sh}; done
